///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ErkekButton recording.
    /// </summary>
    [TestModule("81218213-392d-4284-aa20-7c8a18eb6a39", ModuleType.Recording, 1)]
    public partial class ErkekButton : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static ErkekButton instance = new ErkekButton();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ErkekButton()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ErkekButton Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Erkek butonuna tıklanıldı
            Report.Log(ReportLevel.Info, "Mouse", "Erkek butonuna tıklanıldı\r\nMouse Left Click item 'ApplicationUnderTest.ErkekButton' at Center.", repo.ApplicationUnderTest.ErkekButtonInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ErkekButton.Click();
            Delay.Milliseconds(0);
            
            // Erkek butonuna tıklanıldığı doğrulandı
            Report.Log(ReportLevel.Info, "Validation", "Erkek butonuna tıklanıldığı doğrulandı\r\nValidating AttributeContains (Class>'active') on item 'ApplicationUnderTest.ErkekButton'.", repo.ApplicationUnderTest.ErkekButtonInfo, new RecordItemIndex(1));
            Validate.AttributeContains(repo.ApplicationUnderTest.ErkekButtonInfo, "Class", "active");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
