///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("889553f1-84a0-4da7-a157-1a57cc84f657", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UEyeOl' at 108;25.", repo.ApplicationUnderTest.UEyeOlInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UEyeOl.Click("108;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UyeOl2' at 154;18.", repo.ApplicationUnderTest.UyeOl2Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UyeOl2.Click("154;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 178;23.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RegisterEmail.Click("178;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 167;37.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RegisterEmail.Click("167;37");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'a' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ekinyasin90{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{LControlKey up}{RMenu up}gmail.com' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("ekinyasin90{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{LControlKey up}{RMenu up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UyeOl2' at 138;41.", repo.ApplicationUnderTest.UyeOl2Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.UyeOl2.Click("138;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ErrorBoxWrapper' at 274;52.", repo.ApplicationUnderTest.ErrorBoxWrapperInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.ErrorBoxWrapper.Click("274;52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 392;34.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.RegisterEmail.Click("392;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.RegisterEmail' at 209;28.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.RegisterEmail.MoveTo("209;28");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.RegisterEmail' at -116;29.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.RegisterEmail.MoveTo("-116;29");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
