///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SepettekiUrunSayisiniArtir recording.
    /// </summary>
    [TestModule("685d3354-efde-4d91-9b10-1b781c311f76", ModuleType.Recording, 1)]
    public partial class SepettekiUrunSayisiniArtir : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static SepettekiUrunSayisiniArtir instance = new SepettekiUrunSayisiniArtir();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SepettekiUrunSayisiniArtir()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SepettekiUrunSayisiniArtir Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.PbBasketItem1.Text' at Center.", repo.ApplicationUnderTest.PbBasketItem1.TextInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.PbBasketItem1.Text.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.PbBasketItem1.Text'.", repo.ApplicationUnderTest.PbBasketItem1.TextInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.PbBasketItem1.Text.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2' with focus on 'ApplicationUnderTest.PbBasketItem1.Text'.", repo.ApplicationUnderTest.PbBasketItem1.TextInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.PbBasketItem1.Text.PressKeys("2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SepetiOnayla' at 47;26.", repo.ApplicationUnderTest.SepetiOnaylaInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SepetiOnayla.Click("47;26");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
