///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SepettekiUrunuDogrula recording.
    /// </summary>
    [TestModule("72777b3c-4dbb-4002-b904-7750309c7de6", ModuleType.Recording, 1)]
    public partial class SepettekiUrunuDogrula : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static SepettekiUrunuDogrula instance = new SepettekiUrunuDogrula();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SepettekiUrunuDogrula()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SepettekiUrunuDogrula Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.PbBasketItem1.PbBasketItem' at Center.", repo.ApplicationUnderTest.PbBasketItem1.PbBasketItemInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.PbBasketItem1.PbBasketItem.MoveTo();
            Delay.Milliseconds(0);
            
            // Sepette bir adet ürün oldugu dogrulandı
            Report.Log(ReportLevel.Info, "Validation", "Sepette bir adet ürün oldugu dogrulandı\r\nValidating Exists on item 'ApplicationUnderTest.PbBasketItem1.PbBasketItem'.", repo.ApplicationUnderTest.PbBasketItem1.PbBasketItemInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ApplicationUnderTest.PbBasketItem1.PbBasketItemInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
