///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrendyolTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9fb9b44c-a0d9-4454-a26c-fa4f04e128ac")]
    public partial class TrendyolTestRepository : RepoGenBaseFolder
    {
        static TrendyolTestRepository instance = new TrendyolTestRepository();
        TrendyolTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TrendyolTestRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder _httpswwwtrendyolcomuyelikcbeqhttps;

        /// <summary>
        /// Gets the singleton class instance representing the TrendyolTestRepository element repository.
        /// </summary>
        [RepositoryFolder("9fb9b44c-a0d9-4454-a26c-fa4f04e128ac")]
        public static TrendyolTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrendyolTestRepository() 
            : base("TrendyolTestRepository", "/", null, 0, false, "9fb9b44c-a0d9-4454-a26c-fa4f04e128ac", ".\\RepositoryImages\\TrendyolTestRepository9fb9b44c.rximgres")
        {
            _applicationundertest = new TrendyolTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _httpswwwtrendyolcomuyelikcbeqhttps = new TrendyolTestRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9fb9b44c-a0d9-4454-a26c-fa4f04e128ac")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("fd0bea56-266d-4f5e-bbef-e1c1c79b767d")]
        public virtual TrendyolTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
        /// </summary>
        [RepositoryFolder("4406b713-694f-4dda-9cd0-765980b4be31")]
        public virtual TrendyolTestRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder HttpsWwwTrendyolComUyelikcbEqhttps
        {
            get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrendyolTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("fd0bea56-266d-4f5e-bbef-e1c1c79b767d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            TrendyolTestRepositoryFolders.PbBasketItem1Folder _pbbasketitem1;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _uyeol2Info;
            RepoItemInfo _errorboxwrapperInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _uyeolInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _erkekbuttonInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _femaleqbuttonqbuttonmediumqfluidInfo;
            RepoItemInfo _erkekInfo;
            TişoertInfoClass _tişoertInfo;
            RepoItemInfo _overlayInfo;
            RepoItemInfo _basketpreviewcontainervisibleInfo;
            RepoItemInfo _guılekısakollutişoertInfo;
            RepoItemInfo _imageoverlaybodyInfo;
            RepoItemInfo _guılekısakollutişoert1Info;
            RepoItemInfo _addtobasketInfo;
            RepoItemInfo _fvrtbtnInfo;
            RepoItemInfo _girişyap1Info;
            RepoItemInfo _girisyap2Info;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _fvrtbtn1Info;
            RepoItemInfo _iheartwdfvrtbtnInfo;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _httpscdndsmcdncomty224productmedInfo;
            RepoItemInfo _pcardwrpprInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _imageoverlayInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sepetegitInfo;
            RepoItemInfo _somesvgtagInfo;
            RepoItemInfo _icloseInfo;
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _sepetionaylaInfo;
            RepoItemInfo _guılekısakollutişoert2Info;
            RepoItemInfo _httpswwwtrendyolcomgirisisproceedpInfo;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _hesabımInfo;
            RepoItemInfo _yardımdestekInfo;
            RepoItemInfo _questionanswerboxInfo;
            RepoItemInfo _ptagİadeadımlarıInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "fd0bea56-266d-4f5e-bbef-e1c1c79b767d", "")
            {
                _pbbasketitem1 = new TrendyolTestRepositoryFolders.PbBasketItem1Folder(this);
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'account-navigation-container']/div/div[1]//div[@innertext='Üye Ol']", ".//div[#'account-navigation-container']//div[@innertext='Üye Ol']", 30000, null, "744ba22e-7380-4621-be2b-88c90137dd06");
                _uyeol2Info = new RepoItemInfo(this, "UyeOl2", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//div[#'login-register']//form/button", 30000, null, "0840ce5f-13eb-4eec-ba00-b421b6aa76b4");
                _errorboxwrapperInfo = new RepoItemInfo(this, "ErrorBoxWrapper", ".//div[#'error-box-wrapper']", ".//div[#'error-box-wrapper']", 30000, null, "c67d889d-efb8-435f-a709-36c5b4a598a7");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "e614e823-83e3-4ea0-81a8-53e5efae7604");
                _uyeolInfo = new RepoItemInfo(this, "UyeOl", ".//div[#'login-register']/div[2]/div/button[2]", ".//div[#'login-register']/div[2]/div/button[2]", 30000, null, "85b15a8c-5c85-458f-940a-faf28c66dce1");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "cd43169c-89d6-4386-8895-befc7a11c785");
                _erkekbuttonInfo = new RepoItemInfo(this, "ErkekButton", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[3]/div/button[2]", ".//div[#'login-register']//form/div[3]/div/button[2]", 30000, null, "62376f97-41a5-4a0b-9d91-644bcf8549af");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "0c760dab-d4f6-4bf6-947e-9194aba02261");
                _femaleqbuttonqbuttonmediumqfluidInfo = new RepoItemInfo(this, "FemaleQButtonQButtonMediumQFluid", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[3]/div/button[1]", ".//div[#'login-register']//form/div[3]/div/button[1]", 30000, null, "35749e62-51be-474a-9f12-8cb0c020e953");
                _erkekInfo = new RepoItemInfo(this, "Erkek", ".//div[#'navigation-wrapper']/nav//a[@innertext='Erkek']", ".//div[#'navigation-wrapper']//a[@innertext='Erkek']", 30000, null, "e12eb799-9038-48a3-9f0e-851de919f595");
                _tişoertInfo = new TişoertInfoClass(this);
                _overlayInfo = new RepoItemInfo(this, "Overlay", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[3]", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[2]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[3]", 30000, null, "08310082-fdad-455f-9386-d2f746f97f76");
                _basketpreviewcontainervisibleInfo = new RepoItemInfo(this, "BasketPreviewContainerVisible", ".//div[#'account-navigation-container']/div/div[2]/div", ".//div[#'account-navigation-container']/div/div[2]/div", 30000, null, "06db9c38-dbc1-457c-8356-01a7f1978102");
                _guılekısakollutişoertInfo = new RepoItemInfo(this, "GuıleKısaKolluTişoert", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[2]/div[1]//span[@title='Guıle Kısa Kollu Tişört']", ".//div[#'search-app']//span[@title='Guıle Kısa Kollu Tişört']", 30000, null, "5a1fcb27-1e2d-4cdd-93b4-13747859be7a");
                _imageoverlaybodyInfo = new RepoItemInfo(this, "ImageOverlayBody", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[2]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "5f05dc53-b48e-4fad-88f7-dbad2cb747aa");
                _guılekısakollutişoert1Info = new RepoItemInfo(this, "GuıleKısaKolluTişoert1", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[3]/?/?/a[@href>'https://www.trendyol.com/']/div[2]/div[1]//span[@title='Guıle Kısa Kollu Tişört']", ".//div[#'search-app']//span[@title='Guıle Kısa Kollu Tişört']", 30000, null, "73069b54-7eb4-4395-ae32-7e4787ddbbdb");
                _addtobasketInfo = new RepoItemInfo(this, "AddToBasket", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[7]/button[@pressed='True' and @text='Sepete Ekle']", "", 30000, null, "16be9416-737a-4a72-9b3d-cc1b39749ff4");
                _fvrtbtnInfo = new RepoItemInfo(this, "FvrtBtn", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[3]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[3]/div[2]/i", 30000, null, "99209ee3-a49c-4bad-b44f-1c9e306cfdb1");
                _girişyap1Info = new RepoItemInfo(this, "GirişYap1", ".//div[#'account-navigation-container']/div/div[1]//div[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//div[@innertext='Giriş Yap']", 30000, null, "5e6422f2-5cc0-467d-9eda-d308688dee76");
                _girisyap2Info = new RepoItemInfo(this, "GirisYap2", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//div[#'login-register']//form/button", 30000, null, "91e3b475-cd90-4eec-8c64-fb9ccd566971");
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "346b94a5-d9f4-4b33-9367-5b6139160af9");
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "fdc3be82-5e9b-43f5-bdb5-4e4982435755");
                _fvrtbtn1Info = new RepoItemInfo(this, "FvrtBtn1", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[4]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[4]/div[2]/i", 30000, null, "ca8aba52-eada-4cfe-bbd9-ddf3a35694a7");
                _iheartwdfvrtbtnInfo = new RepoItemInfo(this, "IHeartWdFvrtBtn", ".//div[#'browsing-gw-homepage']/div/div/div/article[6]/div/div/div[3]/?/?/div[@title>'Metal Tıraş Bıçağı 5''li Poşet']/div[1]/i", ".//div[#'browsing-gw-homepage']//div[@title>'Metal Tıraş Bıçağı 5''li Poşet']/div[1]/i", 30000, null, "66cd05ad-e21e-4860-ab1a-7c6c30ab37ed");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "72d7f04d-6ce5-4668-8eff-2cf27ccb22bb");
                _httpscdndsmcdncomty224productmedInfo = new RepoItemInfo(this, "HttpsCdnDsmcdnComTy224ProductMed", ".//div[#'account-gw-favorites']/div/div[3]//a[@href>'https://www.trendyol.com/']/?/?/img[@src='https://cdn.dsmcdn.com/ty224/product/media/images/20211103/14/164756119/97794756/1/1_org.jpg']", ".//div[#'account-gw-favorites']//img[@src='https://cdn.dsmcdn.com/ty224/product/media/images/20211103/14/164756119/97794756/1/1_org.jpg']", 30000, null, "d513ae38-2ab2-4de5-972d-a317b6f3e97a");
                _pcardwrpprInfo = new RepoItemInfo(this, "PCardWrppr", ".//div[#'account-gw-favorites']/div/div[3]/div/div", ".//div[#'account-gw-favorites']/div/div[3]/div/div", 30000, null, "5fe948c3-08cc-494a-9279-f4dfe3fd2aaa");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//div[#'container']/div[5]/div", ".//div[#'container']/div[5]/div", 30000, null, "55d5a3b5-1903-4993-9e70-a75645810078");
                _imageoverlayInfo = new RepoItemInfo(this, "ImageOverlay", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[4]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div/div[4]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]", 30000, null, "4ed122ba-3574-4dc8-ad2b-68f8d5aa004c");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "df9e8e4b-ad6e-4abe-9b3b-82cf39bf95dd");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "6f57989d-ba7a-4196-b4f0-4b1aba8c3b4a");
                _sepetegitInfo = new RepoItemInfo(this, "SepeteGit", ".//div[#'account-navigation-container']//a[@innertext='Sepete Git']", ".//div[#'account-navigation-container']//a[@innertext='Sepete Git']", 30000, null, "433cfa93-5247-493f-9bc1-9d9e8e2bd445");
                _somesvgtagInfo = new RepoItemInfo(this, "SomeSvgTag", ".//div[#'pb-container']/div/div[3]/div[3]/div[3]/div[1]/div/button[2]/svg", ".//div[#'pb-container']/div/div[3]/div[3]/div[3]/div[1]/div/button[2]/svg", 30000, null, "7bbcfe3e-24f7-4f97-9d8f-d40fbca0b294");
                _icloseInfo = new RepoItemInfo(this, "IClose", ".//div[#'account-gw-favorites']/div/div[3]/div/div/div[4]/i", ".//div[#'account-gw-favorites']/div/div[3]/div/div/div[4]/i", 30000, null, "69dbfbe7-abdb-4396-b11b-6c427362e98b");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//div[#'account-navigation-container']//p[@innertext='Çıkış Yap']", ".//div[#'account-navigation-container']//p[@innertext='Çıkış Yap']", 30000, null, "07eb633c-e91f-4a96-87c9-ea0d9930f3f3");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[1]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']//span[@innertext='Sepeti Onayla']", 30000, null, "2f9774ab-a5f1-404e-9b76-84db395ebe95");
                _guılekısakollutişoert2Info = new RepoItemInfo(this, "GuıleKısaKolluTişoert2", ".//div[#'search-app']/div/div[1]/div[2]/div[5]/div[1]/div/div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[2]/div[1]//span[@title='Guıle Kısa Kollu Tişört']", ".//div[#'search-app']//span[@title='Guıle Kısa Kollu Tişört']", 30000, null, "dd58c2e6-00ad-4f9b-93c2-03c30237a6e9");
                _httpswwwtrendyolcomgirisisproceedpInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComGirisisProceedP", ".//div[#'pb-container']/aside/div/div[1]/a[@href>'https://www.trendyol.com/']", ".//div[#'pb-container']/aside/div/div[1]/a[@href>'https://www.trendyol.com/']", 30000, null, "88046820-4ae7-4792-98e0-3dbb30a10ef6");
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?isProceedPayment=true&cb=%2Fsepetim%2Fodeme']/button", ".//div[#'login-register']//form/button", 30000, null, "d7afda47-b434-4796-accd-1bc10de054cf");
                _hesabımInfo = new RepoItemInfo(this, "Hesabım", ".//div[#'account-navigation-container']//p[@innertext='Hesabım']", ".//div[#'account-navigation-container']//p[@innertext='Hesabım']", 30000, null, "44fcac06-c294-4cf5-b469-577f85c88cad");
                _yardımdestekInfo = new RepoItemInfo(this, "YardımDestek", ".//div[#'headerMain']//ul/?/?/a[@innertext='Yardım & Destek']", ".//div[#'headerMain']//a[@innertext='Yardım & Destek']", 30000, null, "42887824-2ee4-49f5-a35b-a5c27aecbaf4");
                _questionanswerboxInfo = new RepoItemInfo(this, "QuestionAnswerBox", ".//div[#'support-gw']/div/div[2]/div[2]/div[1]/div[2]", ".//div[#'support-gw']/div/div[2]/div[2]/div[1]/div[2]", 30000, null, "c4562856-fe69-4adc-afd8-21af29bea47f");
                _ptagİadeadımlarıInfo = new RepoItemInfo(this, "PTagİadeAdımları", ".//div[#'support-gw']/div/div[2]/div[2]/div[1]//p[@innertext='• İade adımları:']", ".//div[#'support-gw']//p[@innertext='• İade adımları:']", 30000, null, "345d0de1-8547-449d-a989-3c19662e3c58");
            }

            /// <summary>
            /// The TişoertInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("b3222690-c51e-4fc8-9d5d-de70ac7b6855")]
            public class TişoertInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TişoertInfoClass class constructor.
                /// </summary>
                public TişoertInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Tişoert", ".//div[#'navigation-wrapper']/nav/ul/li[2]/div/div/div/div[1]/div/ul/li[1]/a[@innertext='Tişört']", 30000, null, "b3222690-c51e-4fc8-9d5d-de70ac7b6855")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("ecceec45-67b5-4431-9208-8403c6dd5c1e")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("ecceec45-67b5-4431-9208-8403c6dd5c1e");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ecceec45-67b5-4431-9208-8403c6dd5c1e")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ecceec45-67b5-4431-9208-8403c6dd5c1e", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd0bea56-266d-4f5e-bbef-e1c1c79b767d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd0bea56-266d-4f5e-bbef-e1c1c79b767d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("744ba22e-7380-4621-be2b-88c90137dd06")]
            public virtual Ranorex.DivTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("744ba22e-7380-4621-be2b-88c90137dd06")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The UyeOl2 item.
            /// </summary>
            [RepositoryItem("0840ce5f-13eb-4eec-ba00-b421b6aa76b4")]
            public virtual Ranorex.ButtonTag UyeOl2
            {
                get
                {
                    return _uyeol2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The UyeOl2 item info.
            /// </summary>
            [RepositoryItemInfo("0840ce5f-13eb-4eec-ba00-b421b6aa76b4")]
            public virtual RepoItemInfo UyeOl2Info
            {
                get
                {
                    return _uyeol2Info;
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item.
            /// </summary>
            [RepositoryItem("c67d889d-efb8-435f-a709-36c5b4a598a7")]
            public virtual Ranorex.DivTag ErrorBoxWrapper
            {
                get
                {
                    return _errorboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("c67d889d-efb8-435f-a709-36c5b4a598a7")]
            public virtual RepoItemInfo ErrorBoxWrapperInfo
            {
                get
                {
                    return _errorboxwrapperInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("e614e823-83e3-4ea0-81a8-53e5efae7604")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("e614e823-83e3-4ea0-81a8-53e5efae7604")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The UyeOl item.
            /// </summary>
            [RepositoryItem("85b15a8c-5c85-458f-940a-faf28c66dce1")]
            public virtual Ranorex.ButtonTag UyeOl
            {
                get
                {
                    return _uyeolInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The UyeOl item info.
            /// </summary>
            [RepositoryItemInfo("85b15a8c-5c85-458f-940a-faf28c66dce1")]
            public virtual RepoItemInfo UyeOlInfo
            {
                get
                {
                    return _uyeolInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("cd43169c-89d6-4386-8895-befc7a11c785")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("cd43169c-89d6-4386-8895-befc7a11c785")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The ErkekButton item.
            /// </summary>
            [RepositoryItem("62376f97-41a5-4a0b-9d91-644bcf8549af")]
            public virtual Ranorex.ButtonTag ErkekButton
            {
                get
                {
                    return _erkekbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ErkekButton item info.
            /// </summary>
            [RepositoryItemInfo("62376f97-41a5-4a0b-9d91-644bcf8549af")]
            public virtual RepoItemInfo ErkekButtonInfo
            {
                get
                {
                    return _erkekbuttonInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("0c760dab-d4f6-4bf6-947e-9194aba02261")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("0c760dab-d4f6-4bf6-947e-9194aba02261")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The FemaleQButtonQButtonMediumQFluid item.
            /// </summary>
            [RepositoryItem("35749e62-51be-474a-9f12-8cb0c020e953")]
            public virtual Ranorex.ButtonTag FemaleQButtonQButtonMediumQFluid
            {
                get
                {
                    return _femaleqbuttonqbuttonmediumqfluidInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The FemaleQButtonQButtonMediumQFluid item info.
            /// </summary>
            [RepositoryItemInfo("35749e62-51be-474a-9f12-8cb0c020e953")]
            public virtual RepoItemInfo FemaleQButtonQButtonMediumQFluidInfo
            {
                get
                {
                    return _femaleqbuttonqbuttonmediumqfluidInfo;
                }
            }

            /// <summary>
            /// The Erkek item.
            /// </summary>
            [RepositoryItem("e12eb799-9038-48a3-9f0e-851de919f595")]
            public virtual Ranorex.ATag Erkek
            {
                get
                {
                    return _erkekInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Erkek item info.
            /// </summary>
            [RepositoryItemInfo("e12eb799-9038-48a3-9f0e-851de919f595")]
            public virtual RepoItemInfo ErkekInfo
            {
                get
                {
                    return _erkekInfo;
                }
            }

            /// <summary>
            /// The Tişoert item.
            /// </summary>
            [RepositoryItem("b3222690-c51e-4fc8-9d5d-de70ac7b6855")]
            public virtual Ranorex.ATag Tişoert
            {
                get
                {
                    return _tişoertInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Tişoert item info.
            /// </summary>
            [RepositoryItemInfo("b3222690-c51e-4fc8-9d5d-de70ac7b6855")]
            public virtual TişoertInfoClass TişoertInfo
            {
                get
                {
                    return _tişoertInfo;
                }
            }

            /// <summary>
            /// The Overlay item.
            /// </summary>
            [RepositoryItem("08310082-fdad-455f-9386-d2f746f97f76")]
            public virtual Ranorex.DivTag Overlay
            {
                get
                {
                    return _overlayInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Overlay item info.
            /// </summary>
            [RepositoryItemInfo("08310082-fdad-455f-9386-d2f746f97f76")]
            public virtual RepoItemInfo OverlayInfo
            {
                get
                {
                    return _overlayInfo;
                }
            }

            /// <summary>
            /// The BasketPreviewContainerVisible item.
            /// </summary>
            [RepositoryItem("06db9c38-dbc1-457c-8356-01a7f1978102")]
            public virtual Ranorex.DivTag BasketPreviewContainerVisible
            {
                get
                {
                    return _basketpreviewcontainervisibleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BasketPreviewContainerVisible item info.
            /// </summary>
            [RepositoryItemInfo("06db9c38-dbc1-457c-8356-01a7f1978102")]
            public virtual RepoItemInfo BasketPreviewContainerVisibleInfo
            {
                get
                {
                    return _basketpreviewcontainervisibleInfo;
                }
            }

            /// <summary>
            /// The GuıleKısaKolluTişoert item.
            /// </summary>
            [RepositoryItem("5a1fcb27-1e2d-4cdd-93b4-13747859be7a")]
            public virtual Ranorex.SpanTag GuıleKısaKolluTişoert
            {
                get
                {
                    return _guılekısakollutişoertInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GuıleKısaKolluTişoert item info.
            /// </summary>
            [RepositoryItemInfo("5a1fcb27-1e2d-4cdd-93b4-13747859be7a")]
            public virtual RepoItemInfo GuıleKısaKolluTişoertInfo
            {
                get
                {
                    return _guılekısakollutişoertInfo;
                }
            }

            /// <summary>
            /// The ImageOverlayBody item.
            /// </summary>
            [RepositoryItem("5f05dc53-b48e-4fad-88f7-dbad2cb747aa")]
            public virtual Ranorex.DivTag ImageOverlayBody
            {
                get
                {
                    return _imageoverlaybodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody item info.
            /// </summary>
            [RepositoryItemInfo("5f05dc53-b48e-4fad-88f7-dbad2cb747aa")]
            public virtual RepoItemInfo ImageOverlayBodyInfo
            {
                get
                {
                    return _imageoverlaybodyInfo;
                }
            }

            /// <summary>
            /// The GuıleKısaKolluTişoert1 item.
            /// </summary>
            [RepositoryItem("73069b54-7eb4-4395-ae32-7e4787ddbbdb")]
            public virtual Ranorex.SpanTag GuıleKısaKolluTişoert1
            {
                get
                {
                    return _guılekısakollutişoert1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GuıleKısaKolluTişoert1 item info.
            /// </summary>
            [RepositoryItemInfo("73069b54-7eb4-4395-ae32-7e4787ddbbdb")]
            public virtual RepoItemInfo GuıleKısaKolluTişoert1Info
            {
                get
                {
                    return _guılekısakollutişoert1Info;
                }
            }

            /// <summary>
            /// The AddToBasket item.
            /// </summary>
            [RepositoryItem("16be9416-737a-4a72-9b3d-cc1b39749ff4")]
            public virtual Ranorex.ButtonTag AddToBasket
            {
                get
                {
                    return _addtobasketInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToBasket item info.
            /// </summary>
            [RepositoryItemInfo("16be9416-737a-4a72-9b3d-cc1b39749ff4")]
            public virtual RepoItemInfo AddToBasketInfo
            {
                get
                {
                    return _addtobasketInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn item.
            /// </summary>
            [RepositoryItem("99209ee3-a49c-4bad-b44f-1c9e306cfdb1")]
            public virtual Ranorex.ITag FvrtBtn
            {
                get
                {
                    return _fvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("99209ee3-a49c-4bad-b44f-1c9e306cfdb1")]
            public virtual RepoItemInfo FvrtBtnInfo
            {
                get
                {
                    return _fvrtbtnInfo;
                }
            }

            /// <summary>
            /// The GirişYap1 item.
            /// </summary>
            [RepositoryItem("5e6422f2-5cc0-467d-9eda-d308688dee76")]
            public virtual Ranorex.DivTag GirişYap1
            {
                get
                {
                    return _girişyap1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap1 item info.
            /// </summary>
            [RepositoryItemInfo("5e6422f2-5cc0-467d-9eda-d308688dee76")]
            public virtual RepoItemInfo GirişYap1Info
            {
                get
                {
                    return _girişyap1Info;
                }
            }

            /// <summary>
            /// The GirisYap2 item.
            /// </summary>
            [RepositoryItem("91e3b475-cd90-4eec-8c64-fb9ccd566971")]
            public virtual Ranorex.ButtonTag GirisYap2
            {
                get
                {
                    return _girisyap2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The GirisYap2 item info.
            /// </summary>
            [RepositoryItemInfo("91e3b475-cd90-4eec-8c64-fb9ccd566971")]
            public virtual RepoItemInfo GirisYap2Info
            {
                get
                {
                    return _girisyap2Info;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("346b94a5-d9f4-4b33-9367-5b6139160af9")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("346b94a5-d9f4-4b33-9367-5b6139160af9")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("fdc3be82-5e9b-43f5-bdb5-4e4982435755")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("fdc3be82-5e9b-43f5-bdb5-4e4982435755")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn1 item.
            /// </summary>
            [RepositoryItem("ca8aba52-eada-4cfe-bbd9-ddf3a35694a7")]
            public virtual Ranorex.ITag FvrtBtn1
            {
                get
                {
                    return _fvrtbtn1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn1 item info.
            /// </summary>
            [RepositoryItemInfo("ca8aba52-eada-4cfe-bbd9-ddf3a35694a7")]
            public virtual RepoItemInfo FvrtBtn1Info
            {
                get
                {
                    return _fvrtbtn1Info;
                }
            }

            /// <summary>
            /// The IHeartWdFvrtBtn item.
            /// </summary>
            [RepositoryItem("66cd05ad-e21e-4860-ab1a-7c6c30ab37ed")]
            public virtual Ranorex.ITag IHeartWdFvrtBtn
            {
                get
                {
                    return _iheartwdfvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IHeartWdFvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("66cd05ad-e21e-4860-ab1a-7c6c30ab37ed")]
            public virtual RepoItemInfo IHeartWdFvrtBtnInfo
            {
                get
                {
                    return _iheartwdfvrtbtnInfo;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("72d7f04d-6ce5-4668-8eff-2cf27ccb22bb")]
            public virtual Ranorex.PTag Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("72d7f04d-6ce5-4668-8eff-2cf27ccb22bb")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComTy224ProductMed item.
            /// </summary>
            [RepositoryItem("d513ae38-2ab2-4de5-972d-a317b6f3e97a")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComTy224ProductMed
            {
                get
                {
                    return _httpscdndsmcdncomty224productmedInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComTy224ProductMed item info.
            /// </summary>
            [RepositoryItemInfo("d513ae38-2ab2-4de5-972d-a317b6f3e97a")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComTy224ProductMedInfo
            {
                get
                {
                    return _httpscdndsmcdncomty224productmedInfo;
                }
            }

            /// <summary>
            /// The PCardWrppr item.
            /// </summary>
            [RepositoryItem("5fe948c3-08cc-494a-9279-f4dfe3fd2aaa")]
            public virtual Ranorex.DivTag PCardWrppr
            {
                get
                {
                    return _pcardwrpprInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PCardWrppr item info.
            /// </summary>
            [RepositoryItemInfo("5fe948c3-08cc-494a-9279-f4dfe3fd2aaa")]
            public virtual RepoItemInfo PCardWrpprInfo
            {
                get
                {
                    return _pcardwrpprInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("55d5a3b5-1903-4993-9e70-a75645810078")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("55d5a3b5-1903-4993-9e70-a75645810078")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The ImageOverlay item.
            /// </summary>
            [RepositoryItem("4ed122ba-3574-4dc8-ad2b-68f8d5aa004c")]
            public virtual Ranorex.DivTag ImageOverlay
            {
                get
                {
                    return _imageoverlayInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlay item info.
            /// </summary>
            [RepositoryItemInfo("4ed122ba-3574-4dc8-ad2b-68f8d5aa004c")]
            public virtual RepoItemInfo ImageOverlayInfo
            {
                get
                {
                    return _imageoverlayInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("df9e8e4b-ad6e-4abe-9b3b-82cf39bf95dd")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("df9e8e4b-ad6e-4abe-9b3b-82cf39bf95dd")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("6f57989d-ba7a-4196-b4f0-4b1aba8c3b4a")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("6f57989d-ba7a-4196-b4f0-4b1aba8c3b4a")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The SepeteGit item.
            /// </summary>
            [RepositoryItem("433cfa93-5247-493f-9bc1-9d9e8e2bd445")]
            public virtual Ranorex.ATag SepeteGit
            {
                get
                {
                    return _sepetegitInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SepeteGit item info.
            /// </summary>
            [RepositoryItemInfo("433cfa93-5247-493f-9bc1-9d9e8e2bd445")]
            public virtual RepoItemInfo SepeteGitInfo
            {
                get
                {
                    return _sepetegitInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag item.
            /// </summary>
            [RepositoryItem("7bbcfe3e-24f7-4f97-9d8f-d40fbca0b294")]
            public virtual Ranorex.SvgTag SomeSvgTag
            {
                get
                {
                    return _somesvgtagInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag item info.
            /// </summary>
            [RepositoryItemInfo("7bbcfe3e-24f7-4f97-9d8f-d40fbca0b294")]
            public virtual RepoItemInfo SomeSvgTagInfo
            {
                get
                {
                    return _somesvgtagInfo;
                }
            }

            /// <summary>
            /// The IClose item.
            /// </summary>
            [RepositoryItem("69dbfbe7-abdb-4396-b11b-6c427362e98b")]
            public virtual Ranorex.ITag IClose
            {
                get
                {
                    return _icloseInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IClose item info.
            /// </summary>
            [RepositoryItemInfo("69dbfbe7-abdb-4396-b11b-6c427362e98b")]
            public virtual RepoItemInfo ICloseInfo
            {
                get
                {
                    return _icloseInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("07eb633c-e91f-4a96-87c9-ea0d9930f3f3")]
            public virtual Ranorex.PTag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("07eb633c-e91f-4a96-87c9-ea0d9930f3f3")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("2f9774ab-a5f1-404e-9b76-84db395ebe95")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("2f9774ab-a5f1-404e-9b76-84db395ebe95")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The GuıleKısaKolluTişoert2 item.
            /// </summary>
            [RepositoryItem("dd58c2e6-00ad-4f9b-93c2-03c30237a6e9")]
            public virtual Ranorex.SpanTag GuıleKısaKolluTişoert2
            {
                get
                {
                    return _guılekısakollutişoert2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GuıleKısaKolluTişoert2 item info.
            /// </summary>
            [RepositoryItemInfo("dd58c2e6-00ad-4f9b-93c2-03c30237a6e9")]
            public virtual RepoItemInfo GuıleKısaKolluTişoert2Info
            {
                get
                {
                    return _guılekısakollutişoert2Info;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComGirisisProceedP item.
            /// </summary>
            [RepositoryItem("88046820-4ae7-4792-98e0-3dbb30a10ef6")]
            public virtual Ranorex.ATag HttpsWwwTrendyolComGirisisProceedP
            {
                get
                {
                    return _httpswwwtrendyolcomgirisisproceedpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComGirisisProceedP item info.
            /// </summary>
            [RepositoryItemInfo("88046820-4ae7-4792-98e0-3dbb30a10ef6")]
            public virtual RepoItemInfo HttpsWwwTrendyolComGirisisProceedPInfo
            {
                get
                {
                    return _httpswwwtrendyolcomgirisisproceedpInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("d7afda47-b434-4796-accd-1bc10de054cf")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("d7afda47-b434-4796-accd-1bc10de054cf")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The Hesabım item.
            /// </summary>
            [RepositoryItem("44fcac06-c294-4cf5-b469-577f85c88cad")]
            public virtual Ranorex.PTag Hesabım
            {
                get
                {
                    return _hesabımInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Hesabım item info.
            /// </summary>
            [RepositoryItemInfo("44fcac06-c294-4cf5-b469-577f85c88cad")]
            public virtual RepoItemInfo HesabımInfo
            {
                get
                {
                    return _hesabımInfo;
                }
            }

            /// <summary>
            /// The YardımDestek item.
            /// </summary>
            [RepositoryItem("42887824-2ee4-49f5-a35b-a5c27aecbaf4")]
            public virtual Ranorex.ATag YardımDestek
            {
                get
                {
                    return _yardımdestekInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The YardımDestek item info.
            /// </summary>
            [RepositoryItemInfo("42887824-2ee4-49f5-a35b-a5c27aecbaf4")]
            public virtual RepoItemInfo YardımDestekInfo
            {
                get
                {
                    return _yardımdestekInfo;
                }
            }

            /// <summary>
            /// The QuestionAnswerBox item.
            /// </summary>
            [RepositoryItem("c4562856-fe69-4adc-afd8-21af29bea47f")]
            public virtual Ranorex.DivTag QuestionAnswerBox
            {
                get
                {
                    return _questionanswerboxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The QuestionAnswerBox item info.
            /// </summary>
            [RepositoryItemInfo("c4562856-fe69-4adc-afd8-21af29bea47f")]
            public virtual RepoItemInfo QuestionAnswerBoxInfo
            {
                get
                {
                    return _questionanswerboxInfo;
                }
            }

            /// <summary>
            /// The PTagİadeAdımları item.
            /// </summary>
            [RepositoryItem("345d0de1-8547-449d-a989-3c19662e3c58")]
            public virtual Ranorex.PTag PTagİadeAdımları
            {
                get
                {
                    return _ptagİadeadımlarıInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagİadeAdımları item info.
            /// </summary>
            [RepositoryItemInfo("345d0de1-8547-449d-a989-3c19662e3c58")]
            public virtual RepoItemInfo PTagİadeAdımlarıInfo
            {
                get
                {
                    return _ptagİadeadımlarıInfo;
                }
            }

            /// <summary>
            /// The PbBasketItem1 folder.
            /// </summary>
            [RepositoryFolder("22d5a415-2c17-4a09-88c6-170fad982d4f")]
            public virtual TrendyolTestRepositoryFolders.PbBasketItem1Folder PbBasketItem1
            {
                get { return _pbbasketitem1; }
            }
        }

        /// <summary>
        /// The PbBasketItem1Folder folder.
        /// </summary>
        [RepositoryFolder("22d5a415-2c17-4a09-88c6-170fad982d4f")]
        public partial class PbBasketItem1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _pbbasketitemInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _tynumericcounterbuttonInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _itrashInfo;
            RepoItemInfo _buttontagsilInfo;

            /// <summary>
            /// Creates a new PbBasketItem1  folder.
            /// </summary>
            public PbBasketItem1Folder(RepoGenBaseFolder parentFolder) :
                    base("PbBasketItem1", ".//div[#'pb-container']/div/div[3]/div[2]", parentFolder, 30000, null, false, "22d5a415-2c17-4a09-88c6-170fad982d4f", "")
            {
                _pbbasketitemInfo = new RepoItemInfo(this, "PbBasketItem", "", "", 30000, null, "d8be6181-7983-4202-9f9b-81840c016188");
                _textInfo = new RepoItemInfo(this, "Text", "div[3]//input[@type='text']", "", 30000, null, "a4f1f37c-d177-40c9-9299-a56662277616");
                _tynumericcounterbuttonInfo = new RepoItemInfo(this, "TyNumericCounterButton", "div[3]/?/?/div/button[2]", "div[3]/div[1]/div/button[2]", 30000, null, "37aaeb1c-5cfc-4a80-8c62-a69035553886");
                _text1Info = new RepoItemInfo(this, "Text1", ".//input[@type='text']", ".//input[@type='text']", 30000, null, "a13d849e-684e-424a-bced-51fc9378e9f4");
                _itrashInfo = new RepoItemInfo(this, "ITrash", ".//button/i", ".//button/i", 30000, null, "f0026215-4715-4079-8301-51a635051f22");
                _buttontagsilInfo = new RepoItemInfo(this, "ButtonTagSil", ".//button[@innertext='Sil']", ".//button[@innertext='Sil']", 30000, null, "ddf82735-eac6-475a-98ae-743a4cbe47d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("22d5a415-2c17-4a09-88c6-170fad982d4f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("22d5a415-2c17-4a09-88c6-170fad982d4f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PbBasketItem item.
            /// </summary>
            [RepositoryItem("d8be6181-7983-4202-9f9b-81840c016188")]
            public virtual Ranorex.DivTag PbBasketItem
            {
                get
                {
                    return _pbbasketitemInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PbBasketItem item info.
            /// </summary>
            [RepositoryItemInfo("d8be6181-7983-4202-9f9b-81840c016188")]
            public virtual RepoItemInfo PbBasketItemInfo
            {
                get
                {
                    return _pbbasketitemInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("a4f1f37c-d177-40c9-9299-a56662277616")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("a4f1f37c-d177-40c9-9299-a56662277616")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The TyNumericCounterButton item.
            /// </summary>
            [RepositoryItem("37aaeb1c-5cfc-4a80-8c62-a69035553886")]
            public virtual Ranorex.ButtonTag TyNumericCounterButton
            {
                get
                {
                    return _tynumericcounterbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TyNumericCounterButton item info.
            /// </summary>
            [RepositoryItemInfo("37aaeb1c-5cfc-4a80-8c62-a69035553886")]
            public virtual RepoItemInfo TyNumericCounterButtonInfo
            {
                get
                {
                    return _tynumericcounterbuttonInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("a13d849e-684e-424a-bced-51fc9378e9f4")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("a13d849e-684e-424a-bced-51fc9378e9f4")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The ITrash item.
            /// </summary>
            [RepositoryItem("f0026215-4715-4079-8301-51a635051f22")]
            public virtual Ranorex.ITag ITrash
            {
                get
                {
                    return _itrashInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The ITrash item info.
            /// </summary>
            [RepositoryItemInfo("f0026215-4715-4079-8301-51a635051f22")]
            public virtual RepoItemInfo ITrashInfo
            {
                get
                {
                    return _itrashInfo;
                }
            }

            /// <summary>
            /// The ButtonTagSil item.
            /// </summary>
            [RepositoryItem("ddf82735-eac6-475a-98ae-743a4cbe47d7")]
            public virtual Ranorex.ButtonTag ButtonTagSil
            {
                get
                {
                    return _buttontagsilInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagSil item info.
            /// </summary>
            [RepositoryItemInfo("ddf82735-eac6-475a-98ae-743a4cbe47d7")]
            public virtual RepoItemInfo ButtonTagSilInfo
            {
                get
                {
                    return _buttontagsilInfo;
                }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder folder.
        /// </summary>
        [RepositoryFolder("4406b713-694f-4dda-9cd0-765980b4be31")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", "/form[@title>'https://www.trendyol.com/']", parentFolder, 30000, null, true, "4406b713-694f-4dda-9cd0-765980b4be31", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4406b713-694f-4dda-9cd0-765980b4be31")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4406b713-694f-4dda-9cd0-765980b4be31")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
