///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UrunSayisininArtirildiginiDogrula recording.
    /// </summary>
    [TestModule("6426a07b-d5c9-4b80-8c6a-7cd449c8dbcf", ModuleType.Recording, 1)]
    public partial class UrunSayisininArtirildiginiDogrula : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static UrunSayisininArtirildiginiDogrula instance = new UrunSayisininArtirildiginiDogrula();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UrunSayisininArtirildiginiDogrula()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UrunSayisininArtirildiginiDogrula Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Urun sayisinin artirildigi dogrulandi
            Report.Log(ReportLevel.Info, "Validation", "Urun sayisinin artirildigi dogrulandi\r\nValidating AttributeNotEqual (Value!='1') on item 'ApplicationUnderTest.PbBasketItem1.Text'.", repo.ApplicationUnderTest.PbBasketItem1.TextInfo, new RecordItemIndex(0));
            Validate.AttributeNotEqual(repo.ApplicationUnderTest.PbBasketItem1.TextInfo, "Value", "1");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
