///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UyeOl recording.
    /// </summary>
    [TestModule("60e55cfd-bb1a-4ab3-97ce-966dc8ee9901", ModuleType.Recording, 1)]
    public partial class UyeOl : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static UyeOl instance = new UyeOl();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UyeOl()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UyeOl Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Uye ol sekmesine tıklanıldı
            Report.Log(ReportLevel.Info, "Mouse", "Uye ol sekmesine tıklanıldı\r\nMouse Left Click item 'ApplicationUnderTest.UyeOl' at 63;37.", repo.ApplicationUnderTest.UyeOlInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UyeOl.Click("63;37");
            Delay.Milliseconds(0);
            
            // Uye ol sekmesi dogrulandı
            Report.Log(ReportLevel.Info, "Validation", "Uye ol sekmesi dogrulandı\r\nValidating Exists on item 'ApplicationUnderTest.UyeOl'.", repo.ApplicationUnderTest.UyeOlInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ApplicationUnderTest.UyeOlInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
